name: timecapsule
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - fastapi
  - uvicorn
  - pydantic
  - python-dotenv
  - pyjwt
  - pytest
  - pyyaml
  - httpx
  - email-validator
  - python-multipart
